version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install 
      - matlab/run-tests:
          test-results-junit: artifacts/test_results/matlab/results.xml
      - store_test_results:
          path: artifacts/test_results
      - store_artifacts:
          path: artifacts/
