version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install                       # previously `wget ...`
      - matlab/run-command:                  # previously `matlab -batch ...`
          command: "disp('Hello World')"
