version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install 
      - matlab/run-tests:
          test-results-junit: artifacts/test_results/matlab/results.xml
          code-coverage-cobertura: artifacts/coverage/codeCoverage.xml          
          source-folder: .;src
      - store_test_results:
          path: artifacts/test_results
      - store_artifacts:
          path: artifacts/
